---
- name: Clean up unused, temporary PHP file with multisite constants that had been used for WordPress Installed checks.
  file:
    state: absent
    path: "{{ deploy_helper.shared_path }}/tmp_multisite_constants.php"

- name: WordPress Installed (non-multisite)?
  block:
    - name: "Invoke 'wp core is-installed' command"
      command: wp core is-installed --skip-plugins --skip-themes
      args:
        chdir: "{{ deploy_helper.new_release_path }}"
      register: wp_installed_singlesite
      changed_when: false
      failed_when: wp_installed_singlesite.stderr | length > 0 or wp_installed_singlesite.rc > 1

    - name: Set "WordPress installed?" result variable (from non-multisite)
      set_fact:
        wp_installed: "{{ wp_installed_singlesite }}"
  when:
    - not project.multisite.enabled | default(false)

- name: WordPress Installed (multisite)?
  block:
    - name: Set variables used in "WordPress Installed (multisite)?" check
      set_fact:
        multisite_non_setup_db_error: "WordPress database error Table '{{ site_env.db_name }}.wp_blogs' doesn't exist"

    - name: "Invoke 'wp core is-installed' command"
      command: wp core is-installed --skip-plugins --skip-themes
      args:
        chdir: "{{ deploy_helper.new_release_path }}"
      register: wp_installed_multisite
      changed_when: false
      failed_when: (wp_installed_multisite.stderr | length > 0 and wp_installed_multisite.stderr is not match(multisite_non_setup_db_error)) or wp_installed_multisite.rc > 1

    - name: Set "WordPress installed?" result variable (from multisite)
      set_fact:
        wp_installed: "{{ wp_installed_multisite }}"
  when:
    - project.multisite.enabled | default(false)


- name: Get WP theme template and stylesheet roots
  shell: >
    {% if not project.multisite.enabled | default(false) %}
      wp option get {{ item }} --skip-plugins --skip-themes
    {% else %}
      wp site list --field=url | xargs -I {} bash -c 'export url="{}"; echo -n "$url " && wp option get {{ item }} --skip-plugins --skip-themes --url=$url || echo'
    {% endif %}
  args:
    chdir: "{{ deploy_helper.current_path }}"
  register: wp_template_root
  changed_when: false
  failed_when: wp_template_root.stderr | default('') is not match("(|.*Could not get '" + item + "' option\. Does it exist\?)")
  when:
    - wp_installed.rc == 0
    - project.update_wp_theme_paths | default(update_wp_theme_paths | default(true)) | bool
  loop:
    - template_root
    - stylesheet_root
